'use client';

import React from 'react';
import Link from 'next/link';
import { 
  HiOutlineShieldCheck, 
  HiOutlineLockClosed, 
  HiOutlineDatabase, 
  HiOutlineUserGroup, 
  HiOutlineMail, 
  HiOutlineArrowLeft 
} from 'react-icons/hi';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#FDFBF7] text-slate-800 font-sans">
      
      {/* Top Navigation */}
      <header className="border-b border-slate-200/70 bg-white/80 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link 
            href="/" 
            className="flex items-center gap-2 text-xs font-bold text-slate-600 hover:text-slate-900 transition"
          >
            <HiOutlineArrowLeft className="text-base" /> Back to Home
          </Link>
          <span className="text-[11px] font-black uppercase tracking-widest text-slate-400">
            Edmiro Institutional Platform
          </span>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-12 sm:py-16 space-y-10">
        
        {/* Header Title */}
        <div className="space-y-3 text-center sm:text-left">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-amber-100 text-amber-900 text-xs font-bold">
            <HiOutlineShieldCheck className="text-base" /> Legal & Data Protection
          </div>
          <h1 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
            Privacy Policy
          </h1>
          <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
            Last Updated: September 2026
          </p>
        </div>

        {/* Introduction Card */}
        <div className="bg-white p-8 rounded-[32px] border border-slate-100 shadow-sm space-y-4 leading-relaxed text-sm text-slate-600">
          <p>
            Welcome to <strong>Edmiro</strong> (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). Edmiro provides an all-in-one school administration, campus enterprise resource planning (ERP), attendance management, dynamic publishing studio, and student information system.
          </p>
          <p>
            This Privacy Policy outlines how we collect, handle, process, and safeguard the personal and operational data generated by institutional administrations, teachers, students, and legal guardians who use our platforms, domains, and connected services.
          </p>
        </div>

        {/* Policy Sections */}
        <div className="space-y-8">
          
          {/* Section 1 */}
          <section className="bg-white p-8 rounded-[32px] border border-slate-100 shadow-sm space-y-3">
            <div className="flex items-center gap-3 text-slate-900">
              <div className="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center text-lg">
                <HiOutlineUserGroup />
              </div>
              <h2 className="text-lg font-black tracking-tight">1. Information We Collect</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              In providing school administration and student management portals, we process information supplied directly by enrolled schools and their authorized administrators:
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-sm text-slate-600 pl-2">
              <li><strong>Institutional Profiles:</strong> School names, affiliations, registration credentials, official contact numbers, addresses, and authorized staff profiles.</li>
              <li><strong>Student & Academic Records:</strong> Student names, grades, enrollment IDs, dates of birth, class assignments, and guardian contact details.</li>
              <li><strong>Financial & Fee Records:</strong> Fee payment records, transaction histories, monthly fee structures, salary disbursements, and institutional accounting ledgers.</li>
              <li><strong>Daily Operations Data:</strong> Student and staff attendance records, calendar events, and published campus notices.</li>
            </ul>
          </section>

          {/* Section 2 */}
          <section className="bg-white p-8 rounded-[32px] border border-slate-100 shadow-sm space-y-3">
            <div className="flex items-center gap-3 text-slate-900">
              <div className="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center text-lg">
                <HiOutlineDatabase />
              </div>
              <h2 className="text-lg font-black tracking-tight">2. Data Architecture &amp; Multi-Tenant Isolation</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              Edmiro utilizes isolated multi-branch structures, custom database configurations, and dedicated cloud storage pipelines (including Google Firebase and Cloudinary).
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-sm text-slate-600 pl-2">
              <li><strong>Isolated School Tenancy:</strong> Each school branch operates in its designated secure scope. Branch administrators cannot access other institutional tenants unless assigned explicit Super Admin credentials.</li>
              <li><strong>Dual-Storage &amp; Independent Databases:</strong> Where requested by partner institutions, dedicated databases are partitioned to guarantee that internal records remain completely detached from public marketing assets.</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section className="bg-white p-8 rounded-[32px] border border-slate-100 shadow-sm space-y-3">
            <div className="flex items-center gap-3 text-slate-900">
              <div className="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center text-lg">
                <HiOutlineLockClosed />
              </div>
              <h2 className="text-lg font-black tracking-tight">3. Data Security &amp; Retention</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              We implement industry-standard administrative, electronic, and physical security measures to safeguard all records against unauthorized alteration, exposure, or destruction:
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-sm text-slate-600 pl-2">
              <li><strong>Session Authentication:</strong> Sessions are authenticated via strict browser cookies and state validation. Passcodes are strictly evaluated through encrypted administrative channels.</li>
              <li><strong>Access Expiration:</strong> Account access is tied to active institutional licensing agreements. When a subscription period concludes, administrative tools are restricted to prevent unauthorized modifications.</li>
              <li><strong>No Third-Party Monetization:</strong> We do not sell, rent, or trade student details, teacher directories, or institutional ledgers to third-party ad networks or marketing aggregators.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section className="bg-white p-8 rounded-[32px] border border-slate-100 shadow-sm space-y-3">
            <div className="flex items-center gap-3 text-slate-900">
              <div className="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center text-lg">
                <HiOutlineMail />
              </div>
              <h2 className="text-lg font-black tracking-tight">4. Contact &amp; Grievance Redressal</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              If an institution, parent, or student wishes to inspect, correct, or request the deletion of their academic profile, or has inquiries regarding this policy, contact our compliance team:
            </p>
            <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/70 text-xs font-bold text-slate-700 space-y-1">
              <p>Edmiro Privacy &amp; Data Security Team</p>
              <p>Email: <a href="mailto:support@edmiro.com" className="text-amber-600 hover:underline">support@edmiro.com</a></p>
              <p>Headquarters: Jaipur, Rajasthan, India</p>
            </div>
          </section>

        </div>

      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200/70 bg-white py-8 text-center text-xs font-semibold text-slate-400">
        <p>Copyright &copy; 2026 Edmiro Platform &bull; All Rights Reserved</p>
      </footer>

    </div>
  );
}